### ISSUE TITLE
Should work for any callables

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia-callhierarchy-extension#1]
Currently it seems like it only works on function calls.
But it should work on any reference or definition of a runtime symbol, i.e. variables, parameters, constructors, globals, etc.

**Comment by AlexTugarev** [comment]
“Called from” calculation considers only methods, but this is a synthetic restriction, and can be relaxed easily, cf. https://github.com/theia-ide/theia-callhierarchy-extension/blob/master/theia-callhierarchy/src/browser/typescript-callhierarchy-service.ts#L137

**Comment by JanKoehnlein** [comment]
Fixed
