### ISSUE TITLE
A Keybinding would be good

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia-callhierarchy-extension#10]
We should add a keybinding for the call hierarchy.
How about [shift]+[alt]+[F12]?

**Comment by JanKoehnlein** [comment]
It is SHIFT-F1

**Comment by svenefftinge** [comment]
It is not shown in the Command Palette, which made me think there is none. We should figure out why that is.

**Comment by JanKoehnlein** [comment]
Fixed
