### ISSUE TITLE
Select behavior

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia-callhierarchy-extension#2]
Currently it is a bit cumbersome to navigate, as I always have to double-click in order to see the actual code and then the call hierarchy loses focus. So if that was not what I was looking for, I have to use the mouse to give the hierarchy focus again.

It would be better, if on select the editor would be opened/activated and the correposnding position(s) would be selected. But the editor should only get focus when I double click (or press enter).

**Comment by JanKoehnlein** [comment]
Fixed
