### ISSUE TITLE
Move to theia repo

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/theia-callhierarchy-extension#6]
This would have a number of benefits:
- we could much easier pull generic code up, e.g. opening editors without setting focus
- other languages could consume it easier
- the typescript implementation could move to `@theia/typescript`

**Comment by svenefftinge** [comment]
Makes sense, lets do it :)

**Comment by JanKoehnlein** [comment]
https://github.com/theia-ide/theia/pull/1149
