### ISSUE TITLE
Wrong container element

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia-callhierarchy-extension#8]
The view shows the wrong container element.
In belows screenshot the element name should be `doBuild` not `manager`:

<img width="601" alt="screen shot 2018-01-27 at 19 39 20" src="https://user-images.githubusercontent.com/372735/35475172-de547f4e-0399-11e8-9923-2c95ca01e1c7.png">

**Comment by JanKoehnlein** [comment]
It is actually consistent, as we wanted to have fields, variables and parameters to be callable, too.
If you expand `manager` you will see it is called by `doBuild()`. It may not be what you expect in comparison with Eclipse JDT.

Of course we can change it. What would you want to show for calls in initializers of top level constants or properties, e.g.
```
export bar = foo();

class Baz {
   baz = foo();
}

function foo() {}
```

**Comment by svenefftinge** [comment]
I think it should use top-level declarations (within namespaces) and members of classes. But not local variables or functions.

**Comment by JanKoehnlein** [comment]
Fixed in https://github.com/theia-ide/theia/pull/1149/commits/abd5ff9a9b6543c9c6075b2d5cd0a88f6962365b
